# Generated by Django 5.0.6 on 2024-05-26 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.TextField(choices=[('CASHIER', 'Cashier'), ('CONSULTANT', 'Consultant'), ('ACCOUNTANT', 'Accountant')], max_length=10),
        ),
    ]
