# Generated by Django 5.0.6 on 2024-05-27 17:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_invoice_product_remove_order_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='creation_date',
            field=models.DateField(auto_created=datetime.datetime(2024, 5, 27, 17, 52, 20, 531107, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='creation_date',
            field=models.DateField(auto_created=datetime.datetime(2024, 5, 27, 17, 52, 20, 530107, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='product',
            name='creation_date',
            field=models.DateField(auto_created=datetime.datetime(2024, 5, 27, 17, 52, 20, 530107, tzinfo=datetime.timezone.utc)),
        ),
    ]
